LANGUAGE = 'PYTHON'
FIRST_LETTER = LANGUAGE[-1]
print(FIRST_LETTER)
SECOND_LETTER = LANGUAGE[-2]
print(SECOND_LETTER)
THIRD_LETTER =LANGUAGE[-3]
print(THIRD_LETTER)
FOURTH_LETTER = LANGUAGE[-4]
print(FOURTH_LETTER)
FIFTH_LETTER = LANGUAGE[-5]
print(FIFTH_LETTER)
LAST_LETTER = LANGUAGE[-6]
print(LAST_LETTER)