LANGUAGE = 'PYTHON'
FIRST_LETTER = LANGUAGE[0]
print(FIRST_LETTER)
SECOND_LETTER = LANGUAGE[1]
print(SECOND_LETTER)
THIRD_LETTER =LANGUAGE[2]
print(THIRD_LETTER)
FOURTH_LETTER = LANGUAGE[3]
print(FOURTH_LETTER)
FIFTH_LETTER = LANGUAGE[4]
print(FIFTH_LETTER)
LAST_INDEX = len(LANGUAGE) - 1
LAST_LETTER = LANGUAGE[LAST_INDEX]
print(LAST_LETTER)