print('TRUE == TRUE: ' ,True == True)
print('TRUE == FALSE: ' ,True == False)
print('FALSE == FALSE: ' ,False == False)
print('TRUE AND TRUE: ' ,True and True)
print('TRUE OR FALSE: ' , True or False)