print(len('MANGO') == len('AVOCADO'))
print(len('MANGO') != len('AVOCADO'))
print(len('MANGO') < len('AVOCADO'))
print(len('MILK') != len('MEAT'))
print(len('MILK') == len('MEAT'))
print(len('TOMATO') == len('POTATO'))
print(len('PYTHON') > len('DRAGON'))