print('1 IS 1' ,1 is 1)
print('1 IS NOT 2' ,1 is not 2)
print('A IN ABSENT' ,'A' in 'ABSENT')
print('b in ABSENT' , 'b' in 'ABSENT')
print('CODING' in 'CODING FOR ALL')
print('a in an' ,'a' in 'an')
print('4 IS 2 ** 2' ,4 is 2 ** 2)
