FIRST_NAME, LAST_NAME, COUNTRY, CITY, AGE, IS_MARRIED = 'BRIJESH', 'PATEL', 'INDIA', 'JAMNAGAR', 19, False
print(FIRST_NAME, LAST_NAME, COUNTRY, CITY, AGE, IS_MARRIED)
print('FIRST NAME: ' ,FIRST_NAME)
print('LAST NAME: ' ,LAST_NAME)
print('COUNTRY: ' ,COUNTRY)
print('CITY: ' ,CITY)
print('AGE: ' ,AGE)
print('IS MARRIED: ' ,IS_MARRIED)