NEGATIVE_NUMBERS = [-5, -4, -3, -2, -1]
POSITIVE_NUMBERS= [1, 2, 3, 4, 5]
ZERO = [0]
NEGATIVE_NUMBERS.extend(ZERO)
NEGATIVE_NUMBERS.extend(POSITIVE_NUMBERS)
print('INTEGERS:', NEGATIVE_NUMBERS)
