FRUITS = ['BANANA', 'ORANGE', 'MANGO', 'LEMON']
VEGETABLES = ['TOMATO', 'POTATO', 'CABBAGE', 'ONION', 'CARROT']
ANIMAL_PRODUCTS = ['MILK', 'MEAT', 'BUTTER', 'YOGHURT']
WEB_TECHES = ['HTML', 'CSS', 'JS', 'REACT', 'REDUX', 'NODE', 'MANGODB']
COUNTRIES = ['INDIA', 'FINLAND', 'ESTONIA', 'DENMARK', 'SWEDEN', 'NORWAY']

print('FRUITS:', FRUITS)
print('NUMBER OF FRUITS:', len(FRUITS))
print('VEGETABLES:', VEGETABLES)
print('NUMBER OF VEGETABLES:', len(VEGETABLES))
print('ANIMAL_PRODUCTS:', ANIMAL_PRODUCTS)
print('NUMBER OF ANIMAL_PRODUCTS:', len(ANIMAL_PRODUCTS))
print('WEB_TECHES:', WEB_TECHES)
print('NUMBER OF WEB TECHES:', len(WEB_TECHES))
print('COUNTRIES:', COUNTRIES)
print('NUMBER OF COUNTRIES:', len(COUNTRIES))
