MULTILINE_STRING = '''I AM A TEACHER AND ENJOY TEACHING.
I DID NOT FIND ANYTHING AS REWARDING AS EMPOWERING PEOPLE.
THAT IS WHY I CREATED 30 DAYS OF PYTHON CHALLENGE.'''
print(MULTILINE_STRING)

MULTILINE_STRING = """I AM A TEACHER AND ENJOY TEACHING.
I DID NOT FIND ANYTHING AS REWARDING AS EMPOWERING PEOPLE.
THAT IS WHY I CREATED 30 DAYS OF PYTHON CHALLENGE."""
print(MULTILINE_STRING)