FRUITS = ('BANANA', 'ORANGE', 'MANGO', 'LEMON')
FIRST_FRUIT = FRUITS[-4]
print(FIRST_FRUIT)
SECOND_FRUIT = FRUITS[-3]
print(SECOND_FRUIT)
THIRD_FRUIT = FRUITS[-2]
print(THIRD_FRUIT)
LAST_FRUIT = FRUITS[-1]
print(LAST_FRUIT)