FRUITS = ('BANANA', 'ORANGE', 'MANGO', 'LEMON')
ALL_FRUITS = FRUITS[-4:]
print(ALL_FRUITS)
ORANGE_MANGO = FRUITS[-3:-1]
print(ORANGE_MANGO)
ORANGE_TO_THE_REST = FRUITS[-3:]
print(ORANGE_TO_THE_REST)