FRUITS = ['BANANA', 'ORANGE', 'MANGO', 'LEMON']
FIRST_FRUIT = FRUITS[-4]
SECOND_FRUIT = FRUITS[-3]
THIRD_FRUIT = FRUITS[-2]
FOURTH_FRUIT = FRUITS[-1]
print(FIRST_FRUIT)
print(SECOND_FRUIT)
print(THIRD_FRUIT)
print(FOURTH_FRUIT)
