FRUITS = ['BANANA', 'ORANGE', 'MANGO', 'LEMON']
ALL_FRUITS = FRUITS[:-4]
print(ALL_FRUITS)
ORANGE_AND_MANGO = FRUITS[-3:-1]
print(ORANGE_AND_MANGO)
ORANGE_MANGO_LEMON = FRUITS[-3:]
print(ORANGE_MANGO_LEMON)
REVERSE_FRUITS = FRUITS[::-1]
print(REVERSE_FRUITS)
