 '''LAPINDROME IS DEFINED AS A STRING WHICH WHEN SPLIT IN THE MIDDLE, GIVES TWO HALVES HAVING THE SAME CHARACTERS AND SAME FREQUENCY OF EACH
CHARACTER. IF THERE ARE ODD NUMBER OF CHARACTERS IN THE STRING, WE IGNORE THE MIDDLE CHARACTER AND CHECK FOR LAPINDROME. FOR EXAMPLE GAGA IS A 
LAPINDROME, SINCE THE TWO HALVES GA AND GA HAVE THE SAME CHARACTERS WITH SAME FREQUENCY. ALSO, ABCCAB, ROTOR AND XYZXY ARE A FEW EXAMPLES OF
LAPINDROMES. NOTE THAT ABBAAB IS NOT A PALINDROME. THE TWO HALVES CONTAIN THE SAME CHARACTERS BUT THEIR FREQUENCIES DO NOT MATCH.
YOUR TASK IS SIMPLE. GIVEN A STRING, YOU NEED TO TELL IF IT IS A LAPINDROME.


INPUT
FIRST LINE OF INPUT CONTAINS A SINGLE INTEGER T, THE NUMBER OF TEST CASES.
EACH TEST IS A SINGLE LINE CONTAINING A STRING S COMPOSED OF ONLY LOWERCASE ENGLISH ALPHABET.

OUTPUT
FOR EACH TEST CASE, OUTPUT ON A SEPARATE LINE: "YES" IF THE STRING IS A LAPINDROME AND "NO" IF IT IS NOT.

CONSTRAINTS
1 ≤ T ≤ 100
2 ≤ |S| ≤ 1000, WHERE |S| DENOTES THE LENGTH OF S
EXAMPLE

SAMPLE INPUT:
6
GAGA
ABCDE
ROTOR
XYZXY
ABBAAB
ABABC

SAMPLE OUTPUT:
YES
NO
YES
YES
NO
NO'''
T = int(input())
for I in range(T):
    N = input()
    L = len(n)
    if L % 2 == 0:
        B, C = n[:l//2], n[l//2:]
    else:
        b, c = n[:l//2], n[l//2+1:]
    if sorted(b) == sorted(c):
        print("YES")
    else:
        print("NO")