FRUITS = ('BANANA', 'ORANGE', 'MANGO', 'LEMON')
ALL_FRUITS = FRUITS[0:4]
print(ALL_FRUITS)
ALL_FRUITS = FRUITS[0:]
print(ALL_FRUITS)
ORANGE_MANGO = FRUITS[1:3]
print(ORANGE_MANGO)
ORANGE_TO_THE_REST = FRUITS[1:]
print(ORANGE_TO_THE_REST)