FRUITS = ('BANANA', 'ORANGE', 'MANGO', 'LEMON')
FIRST_FRUIT = FRUITS[0]
print(FIRST_FRUIT)
SECOND_FRUIT = FRUITS[1]
print(SECOND_FRUIT)
THIRD_FRUIT = FRUITS[2]
print(THIRD_FRUIT)
LAST_INDEX = len(FRUITS)-1
LAST_FRUIT = FRUITS[LAST_INDEX]
print(LAST_FRUIT)