FRUITS = ['BANANA', 'ORANGE', 'MANGO', 'LEMON']
ALL_FRUITS = FRUITS[0:4]
print(ALL_FRUITS)
ALL_FRUITS = FRUITS[0:]
print(ALL_FRUITS)
ORANGE_AND_MANGO = FRUITS[1:3]
print(ORANGE_AND_MANGO)
ORANGE_MANGO_LEMON = FRUITS[1:]
print(ORANGE_MANGO_LEMON)
ORANGE_AND_LEMON = FRUITS[::2]
print(ORANGE_AND_LEMON)
