LETTER ='P'
print(LETTER)
print(len(LETTER))
GREETING = 'HELLO, WORLD!'
print(GREETING)
GREETING = "HALLO, WORLD!"
print(GREETING)
SENTENCE = "I HOPE YOU ARE ENJOYING 30 DAYS  OF PYTHON CHALLENGE"
print(SENTENCE)