CHALLENGE = 'THIRTYDAYSPYTHON'
print(CHALLENGE.isalnum())

CHALLENGE = '30DAYSPYTHON'
print(CHALLENGE.isalnum())

CHALLENGE = 'THIRTY DAYS OF PYTHON 2022'
print(CHALLENGE.isalnum())

CHALLENGE = 'THIRTY DAYS OF PYTHON 2022'
print(CHALLENGE.isalnum())