FIRST_NAME = 'BRIJESH'
LAST_NAME = 'PATEL'
COUNTRY = 'INDIA'
CITY = 'JAMNAGAR'
AGE = '19'
IS_MARRIED = False
SKILLS = ['HTML', 'CSS', 'BOOTSTRAP', 'NODEJS', 'PYTHON']
PERSON_INFO = {'FIRSTNAME':'BRIJESH', 'LASTNAME':'PATEL', 'COUNTRY':'INDIA', 'CITY':'JAMNAGAR'}

print('FIRST NAME: ' ,FIRST_NAME)
print('FIRST NAME LENGTH: ' ,len(FIRST_NAME))
print('last name: ' ,LAST_NAME)
print('LAST NAME LENGTH: ' ,len(LAST_NAME))
print('COUNTRY: ' ,COUNTRY)
print('COUNTRY LENGTH: ' , len(COUNTRY))
print('CITY: ' ,CITY)
print('CITY LENGTH: ' ,len(CITY))
print('AGE: ' ,AGE)
print('MARRIED: ' ,IS_MARRIED)
print('SKILLS: ' ,SKILLS)
print('PERSON INFORMATION: ' ,PERSON_INFO)
print('PERSON INFORMATION LENGTH: ' ,len(PERSON_INFO))