'''YOU ARE GIVEN N WORDS. SOME WORDS MAY REPEAT. FOR EACH WORD, OUTPUT ITS NUMBER OF OCCURRENCES. THE OUTPUT ORDER SHOULD CORRESPOND WITH THE INPUT ORDER OF APPERENCE OF THE WORD. SEE THE SAMPLE INPUT/OUTPUT FOR CLARIFICATION.
NOTE: EACH INPUT LINE ENDS WITH A "\N" CHARACTER.
CONSTRAINT :
1 <= N <= 10^5
THE SUM OF THE LENGTHS OF ALL THE WORDS DO NOT EXCEED 10^6
ALL THE WORDS ARE COMPOSED OF  LOWERCASE ENGLISH LETTERS ONLY.
INPUT FORMAT :
THE FIRST LINE CONTAINES THE INTEGER, N.
THE NEXT N LINES EACH CONTAIN A WORD.
OUTPUT FORMAT :
OUTPUT 2 LINES.
ON THE FIRST LINE, OUTPUT THE NUMBER OF DISTINCTWORDS FROM THE INPUT.
ON THE SECOND LINE, OUTPUT THE NUMBER OF occurrencesOCCURRENCEFOR EACH DISTINCT WORD ACCRODING TO THEIR APPEARANCE IN THE INPUT.'''
import collections;

N = int(input())
D = collections.OrderedDict()

for i in range(N):
    WORD = input()
    if WORD in D:
        D[WORD] +=1
    else:
        D[WORD] = 1

print(len(D));

for K,V in D.items():
    print(V,end = " ");
